apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
    AWS_ACCESS_KEY_ID: {{ .Values.s3.accessKey | b64enc | quote }}
    AWS_SECRET_ACCESS_KEY: {{ .Values.s3.secretKey | b64enc | quote }}
    S3_REGION: {{ .Values.s3.region | b64enc | quote }}
    S3_BUCKET: {{ .Values.s3.bucket | b64enc | quote }}
    S3_ENDPOINT: {{ .Values.s3.endpoint | b64enc | quote }}
    S3_SSE_KEY: {{ .Values.s3.sseKey | b64enc | quote }}
    PAPERLESS_NAMESPACE: {{ .Values.paperless.namespace | b64enc | quote }}
    PAPERLESS_APP: {{ .Values.paperless.app | b64enc | quote }}
    PAPERLESS_CONTAINER_NAME: {{ .Values.paperless.container_name | b64enc | quote }}
    
