apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: {{ .Values.s3.accessKey }}
    AWS_SECRET_ACCESS_KEY: {{ .Values.s3.secretKey }}
    S3_REGION: {{ .Values.s3.region }}
    S3_BUCKET: {{ .Values.s3.bucket }}
    S3_ENDPOINT: {{ .Values.s3.endpoint }}
    S3_SSE_KEY: {{ .Values.s3.sseKey }}
    PAPERLESS_NAMESPACE: {{ .Values.paperless.namespace }}
    PAPERLESS_APP: {{ .Values.paperless.app }}
    PAPERLESS_CONTAINER_NAME: {{ .Values.paperless.container_name }}
    
