apiVersion: v2
name: helm-paperless-s3-backup
description: A Helm chart for automating Paperless NGX backups to a S3 bucket in Kubernetes with optional encryption.
type: application
version: 0.4.0
appVersion: "1.0.7"
