# Default values for helm-paperless-s3-backup.
name: helm-paperless-s3-backup
cron: "0 4 * * 0"

image:
  repository: pascaaal/docker-awscli-gpg
  tag: v1.0.7

s3:
  accessKey:
  secretKey:
  bucket:
  endpoint: # including https://
  region:
  sseKey:
    # 32 bytes hex key (openssl rand -hex 32) for server-side encryption (encprytion enabled when set)

paperless:
  namespace:
  app: # app label of the paperless pod
  container_name:
